const products = [
  {
    name: "Into the Wild",
    description:
      "In April 1992 a young man from a well-to-do family hitchhiked to Alaska and walked alone into the wilderness north of Mt. McKinley. He had given $25,000 in savings to charity, abandoned his car and most of his possessions, burned all the cash in his wallet, and invented a new life for himself. Four months later, his decomposed body was found by a moose hunter. How Christopher Johnson McCandless came to die is the unforgettable story of Into the Wild. Immediately after graduating from college in 1991, McCandless had roamed through the West and Southwest on a vision quest like those made by his heroes Jack London and John Muir. In the Mojave Desert he abandoned his car, stripped it of its license plates, and burned all of his cash. He would give himself a new name, Alexander Supertramp, and, unencumbered by money and belongings, he would be free to wallow in the raw, unfiltered experiences that nature presented. Craving a blank spot on the map, McCandless simply threw the maps away. Leaving behind his desperate parents and sister, he vanished into the wild. Jon Krakauer constructs a clarifying prism through which he reassembles the disquieting facts of McCandless's short life. Admitting an interst that borders on obsession, he searches for the clues to the drives and desires that propelled McCandless. When McCandless's innocent mistakes turn out to be irreversible and fatal, he becomes the stuff of tabloid headlines and is dismissed for his naiveté, pretensions, and hubris. He is said to have had a death wish but wanting to die is a very different thing from being compelled to look over the edge. Krakauer brings McCandless's uncompromising pilgrimage out of the shadows, and the peril, adversity, and renunciation sought by this enigmatic young man are illuminated with a rare understanding--and not an ounce of sentimentality. Mesmerizing, heartbreaking, Into the Wild is a tour de force. The power and luminosity of Jon Krakauer's stoytelling blaze through every page.",
    count: 5,
    price: 17,
    category: "Biographies/Adventure",
    images: [
      { path: "/images/into-the-wild.jpg" },
    ],
    rating: 5,
    reviewsNumber: 5,
    reviews: [],
    attrs: [{ key: "Binding", value: "soft" }],
  },
  {
    name: "Mr. Penumbra's 24-Hour Bookstore",
    description:
      "",
    count: 5,
    price: 25,
    category: "Computers/Laptops/Lenovo",
    images: [{ path: "/images/mr-penumbra.jpg" },],
    rating: 5,
    reviewsNumber: 5,
    reviews: [],
    attrs: [{ key: "Binding", value: "soft" }],
  },
  {
    name: "Wild: From Lost to Found on the Pacific Crest Trail",
    description: "This memoir tells the story of a woman who, after experiencing a series of personal crises, sets out to hike the Pacific Crest Trail alone, much like McCandless in 'Into the Wild.'",
    count: 5,
    price: 17,
    category: "Biographies/Adventure",
    images: [{ path: "/images/wild.jpg" }],
    rating: 4.5,
    reviewsNumber: 6,
    reviews: [],
    attrs: [{ key: "Binding", value: "soft" }]
  },
  {
    name: "The Call of the Wild",
    description: "This classic adventure novel follows the story of Buck, a domesticated dog who is sold to be a sled dog in the Alaskan wilderness. The novel explores themes of survival and the primal instincts that drive us.",
    count: 5,
    price: 16,
    category: "Fiction/Adventure",
    images: [{ path: "/images/the-call-of-the-wild.jpg" }],
    rating: 4.3,
    reviewsNumber: 4,
    reviews: [],
    attrs: [{ key: "Binding", value: "soft" }]
  },
  {
    name: "Walden",
    description: "Thoreau's account of his two-year experiment in simple living in a small cabin in the woods near Walden Pond is a classic of American literature. Thoreau's embrace of nature and rejection of materialism echoes the themes in 'Into the Wild.'",
    count: 5,
    price: 15,
    category: "Non-fiction/Memoir",
    images: [{ path: "/images/walden.jpg" }],
    rating: 4.8,
    reviewsNumber: 9,
    reviews: [],
    attrs: [{ key: "Binding", value: "soft" }]
  },
  {
    name: "A Walk in the Woods",
    description: "This humorous travelogue follows Bryson and his friend as they attempt to hike the Appalachian Trail. Like McCandless, they encounter both beauty and danger in the wilderness.",
    count: 5,
    price: 10,
    category: "Non-fiction/Travel",
    images: [{ path: "/images/a-walk-in-the-woods.jpg" }],
    rating: 4.1,
    reviewsNumber: 3,
    reviews: [],
    attrs: [{ key: "Binding", value: "soft" }]
  },
  {
    name: "The Snow Leopard",
    description: "This memoir recounts Matthiessen's journey through the Himalayas in search of the elusive snow leopard. Like 'Into the Wild,' the book explores themes of nature, spirituality, and the human desire for adventure and transcendence.",
    count: 5,
    price: 12,
    category: "Non-fiction/Memoir",
    images: [{ path: "/images/the-snow.jpg" }],
    rating: 4.5,
    reviewsNumber: 6,
    reviews: [],
    attrs: [{ key: "Binding", value: "soft" }]
  },
  {
    name: "Endurance: Shackleton's Incredible Voyage",
    description: "In August 1914, polar explorer Ernest Shackleton boarded the Endurance and set sail for Antarctica, where he planned to cross the last uncharted continent on foot. In January 1915, after battling its way through a thousand miles of pack ice and only a day's sail short of its destination, the Endurance became locked in an island of ice. Thus began the legendary ordeal of Shackleton and his crew of twenty-seven men. For ten months the ice-moored Endurance drifted northwest before it was finally crushed between two ice floes. With no options left, Shackleton and a small party set out in the one lifeboat they had left, hoping to find a safe haven on the island of South Georgia. In a narrative that is equal parts adventure and science, Lansing recounts the harrowing journey in which the crew faced extreme cold, starvation, and the constant threat of death. Lansing's gripping account of this historic expedition has been widely hailed as a masterpiece of narrative non-fiction, and has earned its place as one of the greatest survival stories of all time.",
    count: 3,
    price: 18,
    category: "Non-fiction/History",
    images: [{ path: "/images/endurance.jpg" }],
    rating: 4.7,
    reviewsNumber: 4,
    reviews: [],
    attrs: [{ key: "Binding", value: "hard" }]
  },
  {
    name: "Wild",
    description: "At twenty-two, Cheryl Strayed thought she had lost everything. In the wake of her mother's death, her family scattered and her own marriage was soon destroyed. Four years later, with nothing more to lose, she made the most impulsive decision of her life. With no experience or training, driven only by blind will, she would hike more than a thousand miles of the Pacific Crest Trail from the Mojave Desert through California and Oregon to Washington State—and she would do it alone. Told with suspense and style, sparkling with warmth and humor, Wild powerfully captures the terrors and pleasures of one young woman forging ahead against all odds on a journey that maddened, strengthened, and ultimately healed her.",
    count: 7,
    price: 15,
    category: "Non-fiction/Memoir",
    images: [{ path: "/images/wild.jpg" }],
    rating: 4.8,
    reviewsNumber: 9,
    reviews: [],
    attrs: [{ key: "Binding", value: "soft" }]
  },
  {
    Name: "Born to Run",
    Description: "This non-fiction book delves into the science of running and the hidden tribe in Mexico called the Tarahumara, who are renowned for their long-distance running abilities. The author explores the human desire for endurance and the power of natural movement.",
    Count: 3,
    Price: 15,
    Category: "Non-fiction/Sports",
    Images: [{ path: "/images/born-to-run.jpg" }],
    Rating: 4.7,
    ReviewsNumber: 10,
    Reviews: [],
    Attrs: [{ key: "Binding", value: "hardcover" }]
  },
  {
    Name: "Wild",
    Description: "This memoir chronicles the author's solo hike along the Pacific Crest Trail. The book explores themes of nature, spirituality, and the human desire for adventure and transcendence.",
    Count: 7,
    Price: 14,
    Category: "Non-fiction/Memoir",
    Images: [{ path: "/images/wild.jpg" }],
    Rating: 4.4,
    ReviewsNumber: 8,
    Reviews: [],
    Attrs: [{ key: "Binding", value: "paperback" }]
  },
  {
    Name: "Into Thin Air",
    Description: "This non-fiction book recounts the author's experience climbing Mount Everest. The book explores themes of nature, spirituality, and the human desire for adventure and transcendence.",
    Count: 3,
    Price: 15,
    Category: "Non-fiction/Sports",
    Images: [{ path: "/images/into-thin-air.jpg" }],
    Rating: 4.7,
    ReviewsNumber: 10,
    Reviews: [],
    Attrs: [{ key: "Binding", value: "hardcover" }]
  },
  {
    Name: "The Call of the Wild",
    Description: "This classic adventure novel follows Buck, a dog who is stolen from his comfortable life in California and sold into service as a sled dog in the Yukon. The book explores themes of nature, spirituality, and the human desire for adventure and transcendence.",
    Count: 3,
    Price: 15,
    Category: "Fiction/Adventure",
    Images: [{ path: "/images/the-call-of-the-wild.jpg" }],
    Rating: 4.7,
    ReviewsNumber: 10,
    Reviews: [],
    Attrs: [{ key: "Binding", value: "hardcover" }]
  },
  {
    Name: "The Little Prince",
    Description: "This classic children's book follows a young prince who leaves his home planet to travel the universe. The book explores themes of nature, spirituality, and the human desire for adventure and transcendence.",
    Count: 3,
    Price: 15,
    Category: "Fiction/Adventure",
    Images: [{ path: "/images/the-little-prince.jpg" }],
    Rating: 4.7,
    ReviewsNumber: 10,
    Reviews: [],
    Attrs: [{ key: "Binding", value: "hardcover" }]
  },
  {
    Name: "The Hobbit",
    Description: "This classic fantasy novel follows Bilbo Baggins, a hobbit who joins a group of dwarves on a quest to reclaim their treasure from a dragon. The book explores themes of nature, spirituality, and the human desire for adventure and transcendence.",
    Count: 3,
    Price: 15,
    Category: "Fiction/Adventure",
    Images: [{ path: "/images/the-hobbit.jpg" }],
    Rating: 4.7,
    ReviewsNumber: 10,
    Reviews: [],
    Attrs: [{ key: "Binding", value: "hardcover" }]
  },
  {
    Name: "The Lord of the Rings",
    Description: "This classic fantasy novel follows Frodo Baggins, a hobbit who joins a group of dwarves on a quest to reclaim their treasure from a dragon. The book explores themes of nature, spirituality, and the human desire for adventure and transcendence.",
    Count: 3,
    Price: 15,
    Category: "Fiction/Adventure",
    Images: [{ path: "/images/the-lord-of-the-rings.jpg" }],
    Rating: 4.7,
    ReviewsNumber: 10,
    Reviews: [],
    Attrs: [{ key: "Binding", value: "hardcover" }]
  },
  {
    Name: "Elephant Company",
    Description: "This non-fiction book recounts the author's experience working with elephants in the jungles of Burma. The book explores themes of nature, spirituality, and the human desire for adventure and transcendence.",
    Count: 3,
    Price: 15,
    Category: "Non-fiction/Sports",
    Images: [{ path: "/images/elephant-company.jpg" }],
    Rating: 4.7,
    ReviewsNumber: 10,
    Reviews: [],
    Attrs: [{ key: "Binding", value: "hardcover" }]
  },
  {
    Name: "The Alchemist",
    Description: "This classic novel follows a young shepherd who leaves his home to travel the world in search of a treasure. The book explores themes of nature, spirituality, and the human desire for adventure and transcendence.",
    Count: 3,
    Price: 15,
    Category: "Fiction/Adventure",
    Images: [{ path: "/images/the-alchemist.jpg" }],
    Rating: 4.7,
    ReviewsNumber: 10,
    Reviews: [],
    Attrs: [{ key: "Binding", value: "hardcover" }]
  },
  {
    Name: "The Art of Racing in the Rain",
    Description: "This novel follows a dog named Enzo as he recounts the story of his life. The book explores themes of nature, spirituality, and the human desire for adventure and transcendence.",
    Count: 3,
    Price: 15,
    Category: "Fiction/Adventure",
    Images: [{ path: "/images/the-art-of-racing-in-the-rain.jpg" }],
    Rating: 4.7,
    ReviewsNumber: 10,
    Reviews: [],
    Attrs: [{ key: "Binding", value: "hardcover" }]
  },
  {
    Name: "The Power of Now",
    Description: "This non-fiction book explores the concept of mindfulness and the power of living in the present moment. The book explores themes of nature, spirituality, and the human desire for adventure and transcendence.",
    Count: 3,
    Price: 15,
    Category: "Non-fiction/Spirituality",
    Images: [{ path: "/images/the-power-of-now.jpg" }],
    Rating: 4.7,
    ReviewsNumber: 10,
    Reviews: [],
    Attrs: [{ key: "Binding", value: "hardcover" }]
  },
  {
    Name: "Romeo and Juliet",
    Description: "This classic play follows two star-crossed lovers who are caught in a feud between their families. The book explores themes of nature, spirituality, and the human desire for adventure and transcendence.",
    Count: 3,
    Price: 15,
    Category: "Fiction/Adventure/Classics",
    Images: [{ path: "/images/romeo-and-juliet.jpg" }],
    Rating: 4.7,
    ReviewsNumber: 10,
    Reviews: [],
    Attrs: [{ key: "Binding", value: "hardcover" }]
  },
  {
    Name: "The Great Gatsby",
    Description: " THE EYES OH MY GOD THE EYES.",
    Count: 3,
    Price: 15,
    Category: "Fiction/Adventure/Classics",
    Images: [{ path: "/images/the-great-gatsby.jpg" }],
    Rating: 4.7,
    ReviewsNumber: 10,
    Reviews: [],
    Attrs: [{ key: "Binding", value: "hardcover" }]
  },
]

  module.exports = products
